export class Routes {
  static ORDERS: string = "/orders"
  static ORDERS_SLICING: string = "/orders/slicing"
  static ORDERS_BY_CORRELATION: string = "/orders/external"
  static TRADE_BOOK: string = "/trades"
  static HOLDINGS: string = "/holdings"
  static POSITIONS: string = "/positions"
  static POSITIONS_CONVERT: string = "/positions/convert"
  static EDIS: string = "/edis/tpin"
  static EDIS_FORM: string = "/edis/form"
  static EDIS_INQUIRE_ISIN: string = "/edis/inquire/isin"
  static FUND_LIMIT: string = "/fundlimit"
  static HISTORICAL: string = "/charts/historical"
  static HISTORICAL_INTRADAY: string = "/charts/intraday"
}
